---
abstract: 'Simulate HTML formatting for systems (eg twitter) that do not allow it'
author:
  - 'Kevin Mulholland <moodfarm@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Basis-ConvertText2-UtfTransform
requires:
  Acme::LeetSpeak: 0
  App::Basis: 0
  Exporter: 0
  Text::Emoticon: 0
  perl: v5.14.0
  strict: 0
  vars: 0
  warnings: 0
resources:
  repository: git://github.com/27escape/App-Basis-ConvertText2-UtfTransform.git
version: 0.4.0
